namespace :legacy_albums do
  desc "Import albums from an albums.json file generated by the legacy BAITU app"
  task import: :environment do
    # albums.json should be in the tasks directory
    json = File.open('albums.json').read
    data = JSON.parse(json)
    data['albums'].each { |legacy|
      legacy['title'] = legacy['album']
      legacy.delete('album')

      album = Album.new(legacy)
      # album.save!
    }
  end

end
